#!/usr/bin/env zsh

# needs to be set to directory where quiz is living
LOCAL="/usr/local/pkgs/quizzapp"

if git -C $LOCAL fetch origin && git -C $LOCAL diff --quiet HEAD origin/main; then
  echo "no changes in repository"
  exit 0

else
  # pull, build image, stop container and restart
  git -C $LOCAL pull
  $LOCAL/docker-build.sh

  docker compose -f $LOCAL/docker-compose.yml down
  docker compose -f $LOCAL/docker-compose.yml up -d

fi
